void fetch();
void decode(bool knob2);
void execute(bool knob2);
void mA(bool knob2);
void write_back();
void display();
void positive_edge_trigger();
void run_riscvsim(bool knob2);
void reset_proc();
void load_program_memory(char *file_name);
bool iscorrect_execute();
void print_pipeline_register();